# This is a basic workflow to help you get started with Actions

name: python app

# Controls when the workflow will run
on: [push]

env:
    ARTIFACT_NAME: myArtifact
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Python version
        run: python pySample.py        
        
  build:
    needs: [test]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: upload artifact
        uses: actions/upload-artifact@v3
        with:
            name: ${{ env.ARTIFACT_NAME }}
            path: .
        
      - name: Python Syntax Checker
        uses: cclauss/Find-Python-syntax-errors-action@v0.2.0
          
      - name: Python install
        uses: "docker://python:3.9"
        
      - name: Python version
        run: |
            ls -al
            python --version
        
        
        