# This is a basic workflow to help you get started with Actions

name: python app

# Controls when the workflow will run
on: [push]

env:
    ARTIFACT_NAME: myArtifact
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: runIt
        uses: actions/checkout@v3
        run: python pySample.py
        
  # This workflow contains a single job called "build"
  build:
    needs: [test]
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v3

      - name: upload artifact
        uses: actions/upload-artifact@v3
        with:
            name: ${{ env.ARTIFACT_NAME }}
            path: .


      - name: Install requirements
        uses: pip install --quiet --requirement requirements.txt
        
      - name: Unit tests                
        run: python -m pytest --verbose --failtest
        
      - name: Python Syntax Checker
        uses: cclauss/Find-Python-syntax-errors-action@v0.2.0
          
      - name: Python install
        uses: "docker://python:3.9"
        
      - name: Python version
        run: |
            ls -al
            python --version
        

        
        
        